[package]
name = "caas-label"
version = "1.0.0"
authors = []

[addresses]
use_case = "_"

[dev-addresses]
use_case = "0xf"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
caas_framework = { local = "../CaasFramework" }

[dev-dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
caas_framework = { local = "../CaasFramework" }
